### ISSUE TITLE
PciView KeyError: '8'

### ISSUE THREAD

**Issue by ghost** [JussiVJ/vfio-conf#2] opened 2019-02-21 04:16 UTC
Running gui.py gives me the following error:

```
File "gui.py", line 198, in <module>
    PciView = [[ListPciIOMMU[0], ListPciName[0], ListPciIDs[0], ListPciDomain[0], ListPciRev[0], pci_ids[ListPciIDs[0]]],
KeyError: '8'
```
Running in python 3.7.2 on Manjaro

**Comment by JussiVJ** [comment] 2019-02-21 10:43
Send me the output from "lspci -nn"

**Comment by ghost** [comment] 2019-02-22 01:37
lspci -nn returns:

```
00:00.0 Host bridge [0600]: Intel Corporation 8th Gen Core Processor Host Bridge/DRAM Registers [8086:3ec2] (rev 07)
00:01.0 PCI bridge [0604]: Intel Corporation Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Processor PCIe Controller (x16) [8086:1901] (rev 07)
00:02.0 VGA compatible controller [0300]: Intel Corporation UHD Graphics 630 (Desktop) [8086:3e92]
00:14.0 USB controller [0c03]: Intel Corporation 200 Series/Z370 Chipset Family USB 3.0 xHCI Controller [8086:a2af]
00:16.0 Communication controller [0780]: Intel Corporation 200 Series PCH CSME HECI #1 [8086:a2ba]
00:17.0 SATA controller [0106]: Intel Corporation 200 Series PCH SATA controller [AHCI mode] [8086:a282]
00:1b.0 PCI bridge [0604]: Intel Corporation 200 Series PCH PCI Express Root Port #17 [8086:a2e7] (rev f0)
00:1b.3 PCI bridge [0604]: Intel Corporation 200 Series PCH PCI Express Root Port #20 [8086:a2ea] (rev f0)
00:1c.0 PCI bridge [0604]: Intel Corporation 200 Series PCH PCI Express Root Port #1 [8086:a290] (rev f0)
00:1c.4 PCI bridge [0604]: Intel Corporation 200 Series PCH PCI Express Root Port #5 [8086:a294] (rev f0)
00:1d.0 PCI bridge [0604]: Intel Corporation 200 Series PCH PCI Express Root Port #9 [8086:a298] (rev f0)
00:1f.0 ISA bridge [0601]: Intel Corporation Z370 Chipset LPC/eSPI Controller [8086:a2c9]
00:1f.2 Memory controller [0580]: Intel Corporation 200 Series/Z370 Chipset Family Power Management Controller [8086:a2a1]
00:1f.3 Audio device [0403]: Intel Corporation 200 Series PCH HD Audio [8086:a2f0]
00:1f.4 SMBus [0c05]: Intel Corporation 200 Series/Z370 Chipset Family SMBus Controller [8086:a2a3]
00:1f.6 Ethernet controller [0200]: Intel Corporation Ethernet Connection (2) I219-V [8086:15b8]
01:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:1470] (rev c1)
02:00.0 PCI bridge [0604]: Advanced Micro Devices, Inc. [AMD] Device [1022:1471]
03:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XL/XT [Radeon RX Vega 56/64] [1002:687f] (rev c1)
03:00.1 Audio device [0403]: Advanced Micro Devices, Inc. [AMD/ATI] Device [1002:aaf8]
05:00.0 Network controller [0280]: Realtek Semiconductor Co., Ltd. RTL8822BE 802.11a/b/g/n/ac WiFi adapter [10ec:b822]
07:00.0 USB controller [0c03]: ASMedia Technology Inc. ASM2142 USB 3.1 Host Controller [1b21:2142]
08:00.0 Non-Volatile memory controller [0108]: Toshiba America Info Systems NVMe Controller [1179:010f] (rev 01)

```

**Comment by JussiVJ** [comment] 2019-02-22 07:59
My laptop is broken right now, so it can take a few days before I can start properly fixing this. I'd try using python 3.6.

**Comment by ghost** [comment] 2019-02-24 03:27
Trying it with python 3.6 gives the same error, unfortunately

**Comment by JussiVJ** [comment] 2019-03-03 18:41
Sorry for taking so long to respond. I have been having a lot of exams in school recently so I haven't been able to respond. When I run the program with your lspci output it runs fine, but can you run the IOMMU-group.sh program in the resources folder and send me the output and also what distro are you using.

**Comment by ghost** [comment] 2019-03-13 16:57
I don't have access to my PC right now due to travel, but I'm running Manjaro with on linux kernel 4.19

**Comment by JussiVJ** [comment] 2019-03-19 19:22
The problem is most likely fixed on the newest version so give that a try when you get home.

**Closed as completed** 2022-02-09 16:57 UTC
